import type { GlossaryEntry } from "../../lib/encyclopedia-data";

/** English anatomical glossary (same concepts as the es-MX glossary). */
export const glossaryEnUS: readonly GlossaryEntry[] = [
  { term: "Acinus", definition: "A grape-like secretory unit of an exocrine gland; in the pancreas it produces digestive enzymes.", organId: "pancreas" },
  { term: "Alveolus", definition: "A microscopic sac at the end of the bronchial tree where oxygen and carbon dioxide are exchanged.", organId: "lungs" },
  { term: "Ampulla of Vater", definition: "The junction of the common bile duct and the pancreatic duct that opens into the duodenum.", organId: "pancreas" },
  { term: "Aorta", definition: "The body's main artery; it arises from the left ventricle and distributes oxygenated blood.", organId: "heart" },
  { term: "Atrium", definition: "An upper chamber of the heart that receives blood returning through the veins.", organId: "heart" },
  { term: "Bile", definition: "A liver secretion that emulsifies fats and eliminates bilirubin and cholesterol.", organId: "liver" },
  { term: "Bronchus", definition: "An airway that carries air from the trachea into each lung.", organId: "lungs" },
  { term: "Cardiomyocyte", definition: "A striated, branched cardiac muscle cell joined to its neighbors by intercalated discs.", organId: "heart" },
  { term: "Cerebellum", definition: "The part of the brain in the posterior fossa that coordinates balance and fine movement.", organId: "brain" },
  { term: "Cone", definition: "A retinal photoreceptor responsible for color vision and visual acuity.", organId: "eyeball" },
  { term: "Cornea", definition: "The clear, avascular front layer of the eye that provides most of its focusing power.", organId: "eyeball" },
  { term: "Cerebral cortex", definition: "The outer gray-matter layer of the brain, seat of higher cognitive functions.", organId: "brain" },
  { term: "Lens", definition: "The biconvex lens of the eye that changes its curvature to focus at different distances.", organId: "eyeball" },
  { term: "Dermatome", definition: "An area of skin supplied by the sensory fibers of a single spinal nerve root.", organId: "skin" },
  { term: "Dermis", definition: "The connective-tissue layer beneath the epidermis that contains vessels, nerves and skin appendages.", organId: "skin" },
  { term: "Diastole", definition: "The phase of the cardiac cycle in which the myocardium relaxes and the chambers fill with blood.", organId: "heart" },
  { term: "Duodenum", definition: "The first segment of the small intestine, where bile and pancreatic juice arrive.", organId: "intestine" },
  { term: "Epidermis", definition: "The outermost layer of the skin, made of keratinized stratified squamous epithelium.", organId: "skin" },
  { term: "Erythropoietin", definition: "A kidney hormone that stimulates red blood cell production in the bone marrow.", organId: "kidneys" },
  { term: "Fovea", definition: "A central pit of the retina with the highest density of cones; it provides the sharpest vision.", organId: "eyeball" },
  { term: "Cardiac output", definition: "The volume of blood the heart pumps per minute; heart rate times stroke volume.", organId: "heart" },
  { term: "Glomerulus", definition: "A tuft of kidney capillaries where plasma is filtered into Bowman's capsule.", organId: "kidneys" },
  { term: "Hepatocyte", definition: "The functional liver cell, responsible for metabolism, protein synthesis and bile production.", organId: "liver" },
  { term: "Hilum", definition: "The region of an organ where vessels, nerves and ducts enter and leave." },
  { term: "Hypodermis", definition: "The deepest layer of the skin, made mostly of adipose tissue.", organId: "skin" },
  { term: "Ileum", definition: "The final segment of the small intestine, where vitamin B12 and bile salts are absorbed.", organId: "intestine" },
  { term: "Insulin", definition: "A hormone from pancreatic β cells that allows glucose to enter tissues.", organId: "pancreas" },
  { term: "Iris", definition: "The pigmented diaphragm of the eye that regulates pupil size and light entry.", organId: "eyeball" },
  { term: "Islets of Langerhans", definition: "Clusters of pancreatic endocrine cells that secrete insulin, glucagon and somatostatin.", organId: "pancreas" },
  { term: "Hepatic lobule", definition: "The hexagonal structural unit of the liver, organized around a central vein.", organId: "liver" },
  { term: "Melanocyte", definition: "A neural-crest-derived cell that produces melanin in the basal layer of the epidermis.", organId: "skin" },
  { term: "Meninges", definition: "The membranes surrounding the brain and spinal cord: dura mater, arachnoid and pia mater.", organId: "brain" },
  { term: "Mesentery", definition: "A peritoneal fold that anchors the intestine to the posterior abdominal wall and carries its vessels.", organId: "intestine" },
  { term: "Microbiota", definition: "The community of microorganisms living in the gut that takes part in digestion and immunity.", organId: "intestine" },
  { term: "Nephron", definition: "The functional unit of the kidney, made of the renal corpuscle and the tubular system.", organId: "kidneys" },
  { term: "Pneumocyte", definition: "An alveolar epithelial cell: type I allows gas exchange and type II produces surfactant.", organId: "lungs" },
  { term: "Neuron", definition: "An excitable nervous-system cell that transmits information through electrical and chemical signals.", organId: "brain" },
  { term: "Sinoatrial node", definition: "The heart's natural pacemaker, located in the right atrium.", organId: "heart" },
  { term: "Pericardium", definition: "A double-layered fibroserous sac that surrounds and protects the heart.", organId: "heart" },
  { term: "Peristalsis", definition: "Coordinated muscular contractions that move contents along the digestive tract.", organId: "intestine" },
  { term: "Pleura", definition: "A double-layered serous membrane covering the lungs and the inner chest wall.", organId: "lungs" },
  { term: "Circle of Willis", definition: "An arterial ring at the base of the brain linking the carotid and vertebrobasilar systems.", organId: "brain" },
  { term: "Renin", definition: "A kidney enzyme that starts the renin-angiotensin-aldosterone system to regulate blood pressure.", organId: "kidneys" },
  { term: "Retina", definition: "The inner neural layer of the eye that turns light into nerve impulses.", organId: "eyeball" },
  { term: "Retroperitoneal", definition: "Located behind the parietal peritoneum, like the kidneys, the pancreas and most of the duodenum." },
  { term: "Couinaud segments", definition: "The eight functional segments of the liver defined by their blood supply; they guide liver surgery.", organId: "liver" },
  { term: "Sinusoid", definition: "A capillary with a discontinuous wall, like those of the liver, allowing broad exchange with the blood.", organId: "liver" },
  { term: "Systole", definition: "The phase of the cardiac cycle in which the myocardium contracts and ejects blood.", organId: "heart" },
  { term: "Surfactant", definition: "A mixture of lipids and proteins that lowers alveolar surface tension and prevents lung collapse.", organId: "lungs" },
  { term: "Intestinal villus", definition: "A finger-like projection of the small-intestine mucosa that expands the absorptive surface.", organId: "intestine" },
  { term: "Portal vein", definition: "The vein that carries nutrient-rich blood from the intestine and spleen to the liver.", organId: "liver" },
  { term: "Ventricle", definition: "A lower chamber of the heart that pumps blood to the lungs or the rest of the body.", organId: "heart" },
];
