import type { OrganId } from "../../lib/anatomy-data";
import type { OrganText } from "../types";

/** English text for each organ. Geometry, assets and hotspot positions live in `anatomy-data`. */
export const organsEnUS: Record<OrganId, OrganText> = {
  heart: {
    name: "Heart",
    system: "Cardiovascular system",
    description: "A muscular organ that pumps blood throughout the body, delivering oxygen and nutrients to every cell.",
    poetic: "The tireless pump",
    size: "About the size of your fist",
    weight: "250–350 g",
    location: "Behind the sternum, slightly to the left",
    function: "Circulates oxygenated blood",
    dailyFact: "Beats about 100,000 times a day",
    medical: "Its electrical rhythm coordinates every heartbeat.",
    bloodSupply: "Left and right coronary arteries",
    funFact: "It beats roughly 2.5 billion times over a lifetime — and starts before birth.",
    tissue: "Cardiac muscle tissue",
    comparison: "Heart vs. brain",
    conditions: ["Coronary artery disease", "Arrhythmia", "Valvular heart disease", "Heart failure", "Cardiomyopathy", "Myocarditis", "Atrial fibrillation", "Congenital heart disease"],
    quiz: {
      question: "Which statement best describes the heart?",
      options: ["A muscular organ that pumps blood throughout the body", "A gland that produces insulin", "A muscle that only activates during sleep"],
      explanation: "The heart is a hollow muscular organ that drives blood through the circulatory system, delivering oxygen and nutrients to every cell.",
    },
    hotspots: {
      aorta: { label: "Aorta", detail: "Main artery" },
      "left-atrium": { label: "Left atrium", detail: "Receives oxygenated blood" },
      "right-atrium": { label: "Right atrium", detail: "Receives venous blood" },
      "left-ventricle": { label: "Left ventricle", detail: "Pumps to the body" },
      "right-ventricle": { label: "Right ventricle", detail: "Pumps to the lungs" },
      mitral: { label: "Mitral valve", detail: "Prevents backflow of blood" },
    },
  },
  brain: {
    name: "Brain",
    system: "Nervous system",
    description: "The body's command center, integrating sensation, memory, emotion and precise movement.",
    poetic: "The inner universe",
    size: "About two clenched fists",
    weight: "1.3–1.4 kg",
    location: "Protected within the skull",
    function: "Processes and coordinates nerve signals",
    dailyFact: "Uses about 20% of the body's energy",
    medical: "Billions of neurons communicate through electrical and chemical signals.",
    bloodSupply: "Internal carotid and vertebral arteries",
    funFact: "It has no pain receptors of its own: a headache is felt in the surrounding tissues.",
    tissue: "Cerebral cortex",
    comparison: "Brain vs. eye",
    conditions: ["Migraine", "Stroke", "Neurodegenerative disease", "Epilepsy", "Traumatic brain injury", "Meningitis", "Multiple sclerosis", "Brain aneurysm"],
    quiz: {
      question: "Which brain lobe is mainly responsible for planning and voluntary movement?",
      options: ["Frontal lobe", "Occipital lobe", "Temporal lobe"],
      explanation: "The frontal lobe coordinates planning, judgment and control of voluntary movement.",
    },
    hotspots: {
      frontal: { label: "Frontal lobe", detail: "Planning and movement" },
      parietal: { label: "Parietal lobe", detail: "Sensory integration" },
      temporal: { label: "Temporal lobe", detail: "Memory and hearing" },
      cerebellum: { label: "Cerebellum", detail: "Balance and coordination" },
    },
  },
  lungs: {
    name: "Lungs",
    system: "Respiratory system",
    description: "Paired organs that take in air and exchange oxygen for carbon dioxide across a vast, delicate surface.",
    poetic: "The breath of life",
    size: "Each about 25 cm tall",
    weight: "About 1 kg combined",
    location: "On either side of the heart, inside the rib cage",
    function: "Exchanges oxygen for carbon dioxide",
    dailyFact: "Moves about 11,000 L of air a day",
    medical: "The alveoli fold a tennis-court-sized exchange surface into the chest.",
    bloodSupply: "Pulmonary and bronchial arteries",
    funFact: "The right lung has three lobes and the left only two, leaving room for the heart.",
    tissue: "Alveolar tissue",
    comparison: "Lungs vs. heart",
    conditions: ["Asthma", "COPD", "Pneumonia", "Pulmonary embolism", "Pulmonary fibrosis", "Bronchitis", "Cystic fibrosis", "Lung cancer"],
    quiz: {
      question: "What is the main function of the lungs?",
      options: ["Filtering the blood", "Exchanging oxygen for carbon dioxide", "Producing insulin"],
      explanation: "In the alveoli, oxygen passes into the blood and carbon dioxide is removed from the body.",
    },
    hotspots: {
      trachea: { label: "Trachea", detail: "Carries air to the lungs" },
      "right-lung": { label: "Right lung", detail: "Three lobes" },
      "left-lung": { label: "Left lung", detail: "Two lobes, room for the heart" },
      bronchus: { label: "Bronchus", detail: "Branching airway" },
      base: { label: "Lung base", detail: "Rests on the diaphragm" },
    },
  },
  liver: {
    name: "Liver",
    system: "Digestive system",
    description: "A remarkable metabolic organ that filters the blood, processes nutrients and produces bile.",
    poetic: "The silent alchemist",
    size: "About the size of an American football",
    weight: "1.4–1.6 kg",
    location: "Right upper abdomen",
    function: "Metabolism, detoxification and bile production",
    dailyFact: "Performs more than 500 different functions",
    medical: "It can regenerate a considerable portion of lost tissue.",
    bloodSupply: "Hepatic artery and portal vein",
    funFact: "It's the only human organ able to regrow to full size from a fraction of itself.",
    tissue: "Hepatic lobules",
    comparison: "Liver vs. intestine",
    conditions: ["Fatty liver disease", "Hepatitis", "Cirrhosis", "Gallstones", "Hemochromatosis", "Liver cancer", "Autoimmune hepatitis", "Portal hypertension"],
    quiz: {
      question: "What makes the liver unique among human organs?",
      options: ["It has no blood vessels", "It can regenerate to its full size", "It cannot become diseased"],
      explanation: "The liver is the only human organ able to regenerate its full mass from a fraction of the original tissue.",
    },
    hotspots: {
      "right-lobe": { label: "Right lobe", detail: "The largest hepatic lobe" },
      "left-lobe": { label: "Left lobe", detail: "Crosses the midline" },
      portal: { label: "Portal vein", detail: "Nutrient-rich inflow" },
    },
  },
  kidneys: {
    name: "Kidneys",
    system: "Urinary system",
    description: "Paired filtering organs that regulate fluids, electrolytes, blood pressure and waste removal.",
    poetic: "The master filters",
    size: "Each about the size of a computer mouse",
    weight: "120–170 g each",
    location: "On either side of the spine, below the ribs",
    function: "Filters blood and forms urine",
    dailyFact: "Filters about 180 L of fluid a day",
    medical: "Nephrons fine-tune the chemistry of the bloodstream.",
    bloodSupply: "Renal arteries",
    funFact: "They reclaim almost everything they filter: only 1–2 L leave the body as urine.",
    tissue: "Renal cortex",
    comparison: "Kidneys vs. liver",
    conditions: ["Kidney stones", "Chronic kidney disease", "Urinary tract infection", "Glomerulonephritis", "Polycystic kidney disease", "Renal hypertension", "Acute kidney injury", "Nephrotic syndrome"],
    quiz: {
      question: "What is the main function of the kidneys?",
      options: ["Producing bile", "Pumping blood", "Filtering blood and forming urine"],
      explanation: "The kidneys filter blood plasma, regulate fluid and electrolyte balance, and form urine.",
    },
    hotspots: {
      cortex: { label: "Renal cortex", detail: "Outer filtering layer" },
      medulla: { label: "Renal medulla", detail: "Concentrates urine" },
      ureter: { label: "Ureter", detail: "Carries urine" },
    },
  },
  eyeball: {
    name: "Eye",
    system: "Sensory system",
    description: "A precision sensory organ that turns focused light into neural signals interpreted as vision.",
    poetic: "A window made of light",
    size: "About 24 mm in diameter",
    weight: "About 7.5 g",
    location: "Inside the bony orbit",
    function: "Captures and focuses light",
    dailyFact: "Makes thousands of tiny movements a day",
    medical: "The retina is an extension of the central nervous system.",
    bloodSupply: "Ophthalmic artery",
    funFact: "The cornea has no blood vessels: it takes oxygen directly from the air.",
    tissue: "Retinal layers",
    comparison: "Eye vs. brain",
    conditions: ["Myopia", "Cataracts", "Glaucoma", "Macular degeneration", "Retinal detachment", "Dry eye", "Astigmatism", "Conjunctivitis"],
    quiz: {
      question: "Which eye structure controls how much light gets in?",
      options: ["The cornea", "The iris", "The optic nerve"],
      explanation: "The iris adjusts the size of the pupil to regulate how much light enters the eye.",
    },
    hotspots: {
      cornea: { label: "Cornea", detail: "Clear focusing surface" },
      iris: { label: "Iris", detail: "Controls light entry" },
      optic: { label: "Optic nerve", detail: "Carries visual signals" },
    },
  },
  intestine: {
    name: "Intestine",
    system: "Digestive system",
    description: "A folded digestive tube where nutrients are absorbed and the microbiome supports whole-body health.",
    poetic: "The inner garden",
    size: "6 to 7 m when extended",
    weight: "Varies with its contents",
    location: "Central and lower abdomen",
    function: "Digestion and nutrient absorption",
    dailyFact: "Hosts trillions of microorganisms",
    medical: "Its surface is expanded by folds, villi and microvilli.",
    bloodSupply: "Superior and inferior mesenteric arteries",
    funFact: "Its lining renews every few days: the fastest tissue turnover in the body.",
    tissue: "Intestinal villi",
    comparison: "Intestine vs. liver",
    conditions: ["Irritable bowel syndrome", "Inflammatory bowel disease", "Celiac disease", "Diverticulitis", "Bowel obstruction", "Colorectal polyps", "Crohn's disease", "Lactose intolerance"],
    quiz: {
      question: "What is the main function of the intestine?",
      options: ["Absorbing nutrients during digestion", "Filtering the blood", "Producing thyroid hormones"],
      explanation: "The intestine absorbs nutrients from digested food and hosts the gut microbiome.",
    },
    hotspots: {
      duodenum: { label: "Duodenum", detail: "First segment of the small intestine" },
      jejunum: { label: "Jejunum", detail: "Main absorption region" },
      colon: { label: "Colon", detail: "Reclaims water" },
    },
  },
  pancreas: {
    name: "Pancreas",
    system: "Endocrine system",
    description: "A dual-function gland that releases digestive enzymes into the gut and the hormones that regulate blood glucose.",
    poetic: "The quiet regulator",
    size: "About 15 cm long",
    weight: "70–100 g",
    location: "Behind the stomach, in the upper abdomen",
    function: "Digestive enzymes and insulin",
    dailyFact: "Produces about 1.5 L of enzyme-rich juice a day",
    medical: "The islets of Langerhans release insulin and glucagon to balance blood glucose.",
    bloodSupply: "Splenic and pancreaticoduodenal arteries",
    funFact: "Only about 2% of it makes hormones; the rest is devoted to digestive enzymes.",
    tissue: "Pancreatic acini",
    comparison: "Pancreas vs. liver",
    conditions: ["Pancreatitis", "Type 1 diabetes", "Pancreatic cancer", "Type 2 diabetes", "Exocrine insufficiency", "Pancreatic cysts", "Gallstone pancreatitis", "Insulinoma"],
    quiz: {
      question: "What does the pancreas produce to regulate blood sugar?",
      options: ["Gastric acid", "Bile", "Insulin and glucagon"],
      explanation: "The pancreatic islets of Langerhans release insulin and glucagon, which balance blood glucose levels.",
    },
    hotspots: {
      head: { label: "Head", detail: "Cradled by the duodenum" },
      body: { label: "Body", detail: "Crosses the spine" },
      tail: { label: "Tail", detail: "Reaches the spleen" },
      duct: { label: "Pancreatic duct", detail: "Drains enzymes into the gut" },
    },
  },
  skin: {
    name: "Skin",
    system: "Integumentary system",
    description: "The body's largest organ: a living barrier that senses touch, retains water and regulates temperature.",
    poetic: "The living boundary",
    size: "About 2 m² when spread out",
    weight: "3.5–5 kg",
    location: "Covers the whole body",
    function: "Protects, senses and cools",
    dailyFact: "Sheds about 500 million cells a day",
    medical: "Three layers — epidermis, dermis and hypodermis — each with a distinct role.",
    bloodSupply: "Dermal vascular plexus",
    funFact: "A single square centimeter can hold hundreds of sweat glands and meters of blood vessels.",
    tissue: "Epidermal layers",
    comparison: "Skin vs. intestine",
    conditions: ["Eczema", "Psoriasis", "Melanoma", "Acne vulgaris", "Cellulitis", "Contact dermatitis", "Rosacea", "Vitiligo"],
    quiz: {
      question: "How many main layers does the skin have?",
      options: ["A single layer", "Three: epidermis, dermis and hypodermis", "Five muscle layers"],
      explanation: "The skin is organized into three main layers — epidermis, dermis and hypodermis — each with distinct functions.",
    },
    hotspots: {
      epidermis: { label: "Epidermis", detail: "Outer protective layer" },
      dermis: { label: "Dermis", detail: "Nerves, vessels and glands" },
      hypodermis: { label: "Hypodermis", detail: "Fat and insulation" },
      follicle: { label: "Hair follicle", detail: "Anchors each hair" },
    },
  },
};
